# Collision objects for the planning scene.
# Units: meters and radians.
objects:
  - id: table
    frame_id: base_link
    type: BOX
    dimensions: [1.28, 1.18, 0.04]     # [x, y, z]
    position: { x: -0.29, y: 0.0, z: -0.03 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.00 }

  - id: back
    frame_id: base_link
    type: BOX
    dimensions: [0.1, 1.18, 1.20]    # [x, y, z]
    position: { x: 0.3, y: 0.00, z: 0.6 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.0 }

  - id: front
    frame_id: base_link
    type: BOX
    dimensions: [0.1, 1.18, 1.20]          
    position: { x: -0.88, y: 0.00, z: 0.6 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.0 }

  - id: left
    frame_id: base_link
    type: BOX
    dimensions: [1.28, 0.1, 1.20]          
    position: { x: -0.29, y: 0.55, z: 0.6 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.0 }


  - id: right
    frame_id: base_link
    type: BOX
    dimensions: [1.28, 0.1, 1.20]          
    position: { x: -0.29, y: -0.55, z: 0.6 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.0 }

  - id: top
    frame_id: base_link
    type: BOX
    dimensions: [1.28, 1.18, 0.04]     # [x, y, z]
    position: { x: -0.29, y: 0.0, z: 1.2 }
    rpy:      { roll: 0.0, pitch: 0.0, yaw: 0.0 }
