# # MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager

# # Optional tweaks for the ros2_control interface:
# ros_control_namespace: "/"                # if your ros2_control node is namespaced
# controller_service_call_timeout: 5.0      # seconds (default 3.0)


# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rozum_joint_controller
    
  rozum_joint_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6


